apiVersion: kustomize.config.k8s.io/v1beta1  
kind: Kustomization

resources:
  - deploy_gke.yaml

# Possible additions
configMapGenerator:
  - name: app-config
    literals:
      - ENV=production

secretGenerator:
  - name: app-secret
    literals:
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=secretpassword